### ISSUE TITLE
No such file or directory: '/home/lws/dataset/ZJU-MoCap/CoreView_313/X_smpl_joints.npy'

### ISSUE THREAD

**Issue by liwenssss** [zyhbili/Dual-Space-NeRF#3]
Hi, thanks for your nice work. I want to try your code but find something wrong. By the way, can you offer a pretrained checkpoint?

**Comment by zyhbili** [comment]
**For X_smpl_joints.** I provide the sample X_smpl_joints and the tool to generate them in **tool/**, please pull the latest code. Now it seems bug free to train our model.
**For the pretrained model.** Since i rename the module name in this formal repo, i faced some bugs to load the old ckpt. I would like to fix them in the near future.
